Removal of Prebid SSO
prebid/addressability-framework pull request #127
Opened 2022-04-13 14:14 UTC by lbdvt

"Prebid SSO Data" replaced by User Id and Preferences
"Prebid SSO" replaced by PAF

2022-04-13 19:50 UTC, OlivierChirouze requested changes

2022-04-13 19:50 UTC, OlivierChirouze commented on mvp-spec/operator-requirements.md
> +                O -->> B: User Id and Preferences
No: there are no preferences at this stage

2022-04-13 19:54 UTC, OlivierChirouze reviewed
I think if we merge https://github.com/prebid/addressability-framework/pull/128 first and you rebase your PR, this should be ok.

2022-04-14 07:53 UTC, RomainLofaso approved these changes

2022-04-14 08:54 UTC, OlivierChirouze approved these changes

2022-04-14 09:08 UTC, RomainLofaso approved these changes

2022-04-14 09:08 UTC, merged